version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    tty: true
    volumes:
      - .:/app/
    ports:
      - "8088:8000"