# Generated by Django 4.1.2 on 2023-03-15 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0003_alter_category_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineTranslationAdequacyProject",
            fields=[
                (
                    "machinetranslationproject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.machinetranslationproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.machinetranslationproject",),
        ),
        migrations.CreateModel(
            name="MachineTranslationAdequacyProjectEntry",
            fields=[
                (
                    "projectentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.projectentry",
                    ),
                ),
                ("adequacy", models.FloatField(verbose_name="Adequacy")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.projectentry",),
        ),
        migrations.CreateModel(
            name="MachineTranslationAdequacyProjectUnannotatedEntry",
            fields=[
                (
                    "unannotatedprojectentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.unannotatedprojectentry",
                    ),
                ),
                (
                    "mt_system_translation",
                    models.TextField(verbose_name="Reference Translation"),
                ),
                (
                    "pre_annotation_adequacy",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pre-annotation adequacy"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.unannotatedprojectentry",),
        ),
        migrations.CreateModel(
            name="MachineTranslationFluencyProject",
            fields=[
                (
                    "machinetranslationproject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.machinetranslationproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.machinetranslationproject",),
        ),
        migrations.CreateModel(
            name="MachineTranslationFluencyProjectEntry",
            fields=[
                (
                    "projectentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.projectentry",
                    ),
                ),
                ("fluency", models.FloatField(verbose_name="Fluency")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.projectentry",),
        ),
        migrations.CreateModel(
            name="MachineTranslationFluencyProjectUnannotatedEntry",
            fields=[
                (
                    "unannotatedprojectentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.unannotatedprojectentry",
                    ),
                ),
                (
                    "pre_annotation_fluency",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pre-annotation fluency"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.unannotatedprojectentry",),
        ),
        migrations.RemoveField(
            model_name="machinetranslationprojectunannotatedentry",
            name="unannotatedprojectentry_ptr",
        ),
        migrations.DeleteModel(
            name="MachineTranslationProjectEntry",
        ),
        migrations.DeleteModel(
            name="MachineTranslationProjectUnannotatedEntry",
        ),
    ]
