# Generated by Django 4.1.2 on 2023-03-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projectmanagement", "0004_machinetranslationadequacyproject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinetranslationadequacyprojectentry",
            name="annotator_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="machinetranslationfluencyprojectentry",
            name="annotator_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TextHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "span_start",
                    models.IntegerField(verbose_name="Beginning of text span"),
                ),
                ("span_end", models.IntegerField(verbose_name="End of text span")),
                (
                    "category",
                    models.CharField(max_length=255, verbose_name="Text span category"),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="machinetranslationadequacyprojectentry",
            name="source_text_highlights",
            field=models.ManyToManyField(
                blank=True,
                related_name="adequacy_source_text",
                to="projectmanagement.texthighlight",
                verbose_name="Machine Translation Adequacy Source Text Highlights",
            ),
        ),
        migrations.AddField(
            model_name="machinetranslationadequacyprojectentry",
            name="target_text_highlights",
            field=models.ManyToManyField(
                blank=True,
                to="projectmanagement.texthighlight",
                verbose_name="Machine Translation Adequacy Target Text Highlights",
            ),
        ),
        migrations.AddField(
            model_name="machinetranslationfluencyprojectentry",
            name="target_text_highlights",
            field=models.ManyToManyField(
                blank=True,
                related_name="fluency_source_text",
                to="projectmanagement.texthighlight",
                verbose_name="Machine Translation Fluency Highlights",
            ),
        ),
    ]
