# Generated by Django 4.1.2 on 2023-03-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "projectmanagement",
            "0005_machinetranslationadequacyprojectentry_annotator_comment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NamedEntityRecognitionProject",
            fields=[
                (
                    "project_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.project",),
        ),
        migrations.CreateModel(
            name="NamedEntityRecognitionProjectUnannotatedEntry",
            fields=[
                (
                    "unannotatedprojectentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.unannotatedprojectentry",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.unannotatedprojectentry",),
        ),
        migrations.AlterField(
            model_name="category",
            name="key_binding",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Key Bindnig"
            ),
        ),
        migrations.CreateModel(
            name="NERTextHighlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "span_start",
                    models.IntegerField(verbose_name="Beginning of text span"),
                ),
                ("span_end", models.IntegerField(verbose_name="End of text span")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="projectmanagement.category",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="NamedEntityRecognitionProjectEntry",
            fields=[
                (
                    "projectentry_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projectmanagement.projectentry",
                    ),
                ),
                (
                    "ner_text_highlights",
                    models.ManyToManyField(
                        blank=True,
                        to="projectmanagement.texthighlight",
                        verbose_name="Named Entity Recognition Text Highlights",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("projectmanagement.projectentry",),
        ),
    ]
