# Generated by Django 4.1.2 on 2023-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0006_namedentityrecognitionproject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="namedentityrecognitionprojectentry",
            name="ner_text_highlights",
            field=models.ManyToManyField(
                blank=True,
                to="projectmanagement.nertexthighlight",
                verbose_name="Named Entity Recognition Text Highlights",
            ),
        ),
    ]
