# Generated by Django 4.1.2 on 2023-04-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0008_project_character_level_selection"),
    ]

    operations = [
        migrations.AddField(
            model_name="texthighlight",
            name="mistranslation_source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanagement.texthighlight",
            ),
        ),
    ]
