# Generated by Django 4.1.2 on 2023-05-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectmanagement", "0009_texthighlight_mistranslation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="machinetranslationadequacyprojectunannotatedentry",
            name="reference_translation",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="machinetranslationfluencyprojectunannotatedentry",
            name="reference_translation",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddField(
            model_name="machinetranslationproject",
            name="source_language",
            field=models.CharField(default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="machinetranslationproject",
            name="target_language",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
