# Generated by Django 4.1.2 on 2023-03-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projectmanagement", "0001_initial"),
        ("annotators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateannotator",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="projectmanagement.project",
                verbose_name="Project",
            ),
        ),
    ]
